version: "3"
services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: comment
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
